name: Build & Temporary Release

on:
  push:
    branches:
      - main

env:
  WORKING_DIR: ./tabletalk_mobile

jobs:
  build:
    name: Build & Temporary Release
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "17"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.0"
          channel: "stable"
      - name: Get dependencies
        working-directory: ${{ env.WORKING_DIR }}
        run: flutter pub get
      - name: Run tests
        working-directory: ${{ env.WORKING_DIR }}
        continue-on-error: true
        run: flutter test
      - name: Set up env
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          touch .env
          echo "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}" >> .env
          echo "AUTH0_DOMAIN=${{ secrets.AUTH0_DOMAIN }}" >> .env
          echo "AUTH0_CLIENT_ID=${{ secrets.AUTH0_CLIENT_ID }}" >> .env
          echo "AUTH0_AUDIENCE=${{ secrets.AUTH0_AUDIENCE }}" >> .env
          echo "CORE_API_URL=${{ secrets.CORE_API_URL }}" >> .env
      - name: Build APK
        working-directory: ${{ env.WORKING_DIR }}
        run: flutter build apk --debug --split-per-abi
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/debug/*"
          allowUpdates: true
          tag: ${{ github.run_number }}
      - name: Build IPA
        working-directory: ${{ env.WORKING_DIR }}
        continue-on-error: true
        run: |
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        continue-on-error: true
        with:
          artifacts: "build/app/outputs/apk/debug/*,build/ios/iphoneos/app.ipa"
          allowUpdates: true
          tag: ${{ github.run_number }}
