name: Build & Release

on:
  push:
    branches:
      - main

env:
  WORKING_DIR: ./tabletalk_mobile

jobs:
  build:
    name: Build & Release
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.0"
          channel: "stable"
      - name: Get dependencies
        working-directory: ${{ env.WORKING_DIR }}
        run: flutter pub get
      - name: Run tests
        working-directory: ${{ env.WORKING_DIR }}
        continue-on-error: true
        run: flutter test
      - name: Build APK
        working-directory: ${{ env.WORKING_DIR }}
        run: flutter build apk --debug --split-per-abi
      - name: Build IPA
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/debug/*,build/ios/iphoneos/app.ipa"
          tag: v1.0.${{ github.run_number }}
